//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class UserInfo : IEntityDto
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public int UserId { get; set; }
        public int UserInfoType { get; set; }
    
        public virtual UserAcc UserAcc { get; set; }
        public virtual UserInfoType UserInfoType1 { get; set; }
    }
}
