//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageUnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageUnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE [dbo].[Rating]
        ///DROP TABLE [dbo].[AccessRight]
        ///DROP TABLE [dbo].[AccessRightType]
        ///DROP TABLE [dbo].[ClientAdmin]
        ///DROP TABLE [dbo].[EntityInfo]
        ///DROP TABLE [dbo].[EntityInfoType]
        ///DROP TABLE [dbo].[UserInfo]
        ///DROP TABLE [dbo].[UserInfoType]
        ///DROP TABLE [dbo].[Entity]
        ///DROP TABLE [dbo].[EntityType]
        ///DROP TABLE [dbo].[Client]
        ///DROP TABLE [dbo].[UserAcc]
        ///
        ///
        ///CREATE TABLE Client(
        ///	Id Int IDENTITY Primary Key,
        ///	Name varchar(256) NOT NULL,
        ///	Token varchar(256) NOT NULL
        ///);
        ///
        ///
        ///CREATE TABLE Entity [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string datamodel {
            get {
                return ResourceManager.GetString("datamodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO AccessRightType (Name) VALUES  (&apos;Buyer&apos;)
        ///INSERT INTO AccessRightType (Name) VALUES  (&apos;Owner&apos;)
        ///
        ///
        ///INSERT INTO UserInfoType (Type) VALUES  (&apos;Email&apos;)
        ///INSERT INTO UserInfoType (Type) VALUES  (&apos;Firstname&apos;)
        ///INSERT INTO UserInfoType (Type) VALUES  (&apos;Lastname&apos;)
        ///INSERT INTO UserInfoType (Type) VALUES  (&apos;Location&apos;)
        ///
        ///
        ///INSERT INTO EntityInfoType (Name) VALUES  (&apos;Title&apos;)
        ///INSERT INTO EntityInfoType (Name) VALUES  (&apos;Description&apos;)
        ///INSERT INTO EntityInfoType (Name) VALUES  (&apos;Price&apos;)
        ///INSERT INTO Entit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata {
            get {
                return ResourceManager.GetString("testdata", resourceCulture);
            }
        }
    }
}
