//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class AcessRight : IEntityDto
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public int EntityId { get; set; }
        public int UserId { get; set; }
        public int AccessRightTypeId { get; set; }
    
        public virtual AccessRightType AccessRightType { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual UserAcc UserAcc { get; set; }
    }
}
