//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BNDNEntities : DbContext, IDbContext
    {
        public BNDNEntities()
            : base("name=BNDNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessRightType> AccessRightType { get; set; }
        public DbSet<AcessRight> AcessRight { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<ClientAdmin> ClientAdmin { get; set; }
        public DbSet<Entity> Entity { get; set; }
        public DbSet<EntityInfo> EntityInfo { get; set; }
        public DbSet<EntityInfoType> EntityInfoType { get; set; }
        public DbSet<EntityType> EntityType { get; set; }
        public DbSet<UserAcc> UserAcc { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<UserInfoType> UserInfoType { get; set; }

        public new IDbSet<T> Set<T>() where T : class
        {
            base.Set<T>();
        }
    }
}
